kubernetes/cloud-provider-alibaba-cloud

OWNERS

Since I am the member of  @AliyunContainerService and @kubernetes, so I'd like to add myself to the OWNER file.
cc @cheyang

add myself to the OWNER

---

cloud-controller-manager/alicloud.go
cloud-controller-manager/alicloud_test.go
cloud-controller-manager/controller/route/route_controller.go
cloud-controller-manager/listener_test.go
cloud-controller-manager/listeners.go
cloud-controller-manager/loadbalancer.go
cloud-controller-manager/loadbalancer_test.go
cloud-controller-manager/options.go

Gofmt code

---

cloud-controller-manager/controller/service/service_controller.go

Signed-off-by: Rui Cao <ruicao@alauda.io>

Typo fix: enpoint -> endpoint

---

cloud-controller-manager/alicloud.go

Add the function name to the comment

---

cloud-controller-manager/loadbalancer.go

Delete excess code

---

cmd/cloudprovider/app/controllermanager.go

Signed-off-by: gaozhenhai <gaozh1988@live.com>

Fix log output format

---

docs/zh/usage.md

add zh doc

---

Makefile
docs/zh/usage.md

Fixes some typo here :)
Refine #19

Fix typo & pass tag env for build

---

cloud-controller-manager/alicloud.go
cloud-controller-manager/alicloud_test.go
cloud-controller-manager/clientmgr.go
cloud-controller-manager/controller/route/options.go
cloud-controller-manager/controller/route/route_controller.go
cloud-controller-manager/controller/route/utils_test.go
cloud-controller-manager/routes.go
cloud-controller-manager/routes_test.go
cloud-controller-manager/utils.go
cmd/cloudprovider/app/controllermanager.go
hack/cloud-config.conf
hack/setup.sh
vendor/github.com/denverdino/aliyungo/ecs/vpcs.go

support for multi route-table.

support multi route-table.

---

Dockerfile
Makefile
build/Dockerfile

Ubuntu has many vulnerabilities. Use slim one - Alpine

Use secured base image Alpine

---

cloud-controller-manager/routes.go

withvpc accept multiple route tables

---

Makefile

convert space to tab for Makefile

---

cloud-controller-manager/listeners.go

remove http Remove() implements

---

cloud-controller-manager/clientmgr.go

vpc client refresh token

---

cloud-controller-manager/listeners.go
cloud-controller-manager/options.go

normalize service annotation

---

cloud-controller-manager/listeners.go

protocol nil pointer

---

Makefile

Signed-off-by: Yuan Sun <yile.sy@alibaba-inc.com>

add unit-test and check in Makefile

---

.circleci/config.yml

Signed-off-by: Yuan Sun <yile.sy@alibaba-inc.com>

add config.yml for circle ci

---

Makefile

Signed-off-by: Yuan Sun <yile.sy@alibaba-inc.com>

add gometalinter installation

---

Makefile

Signed-off-by: Yuan Sun <yile.sy@alibaba-inc.com>

Remove gometalinter installation since a new image is used.

---

cloud-controller-manager/alicloud.go
cloud-controller-manager/privatezone.go

Signed-off-by: bingshen.wbs <bingshen.wbs@alibaba-inc.com>

privatezone support ipv6 loadbalancer

---

cloud-controller-manager/controller/service/controller.go
cloud-controller-manager/framework.go
cloud-controller-manager/instances.go

fix gometalinter issues

---

cloud-controller-manager/alicloud_test.go
cloud-controller-manager/clientmgr.go
cloud-controller-manager/framework.go
cmd/e2e/README.md
cmd/e2e/e2e_test.go
cmd/e2e/framework/flags.go
cmd/e2e/test/service.go
docs/usage.md
docs/zh/usage.md

Add server cookie and forward port test cases.
Update uasge.md and README.md.

add new test cases.

---

cloud-controller-manager/alicloud.go
cloud-controller-manager/controller/node/controller.go

fix remove cloud taints problems

add log for node controller,

---

cloud-controller-manager/controller/service/controller.go

retry with status log

---

cloud-controller-manager/controller/service/context.go

Signed-off-by: xianwei.zw <xianwei.zw@alibaba-inc.com>

Add SERVICE_FORCE_BACKEND_ENI env for serverless kubernetes

---

cloud-controller-manager/controller/service/context.go
cloud-controller-manager/controller/service/controller.go
cloud-controller-manager/framework.go
cloud-controller-manager/listeners.go
cloud-controller-manager/utils/const.go
cloud-controller-manager/vgroups.go

Signed-off-by: xianwei.zw <xianwei.zw@alibaba-inc.com>

code refactoring: isEniBackend and IsENIBackendType

---

cloud-controller-manager/utils/const.go

Allow node backend in serverless kubernetes cluster
Signed-off-by: xianwei.zw <xianwei.zw@alibaba-inc.com>

Minor change for IsENIBackendType

---

cloud-controller-manager/alicloud_test.go
cloud-controller-manager/vgroups.go

batch process for DescribeNetworkInterfaces

---

cloud-controller-manager/controller/route/controller.go

If the ecs is stopped and the node is in unknown status. ccm should not create route to that node,because a stopped node can not do that.
```
c6171f8759d8d4ab5897c54d89d7d844c
Level:Warning 
Kind:Node 
Namespace:default 
Name:cn-beijing.i-2ze8nyz28v9ydi0fx2iu.15d313663b0f3dfa 
Reason:FailedToCreateRoute 
Timestamp:2019-11-01 15:27:04 +0000 UTC 
Message:could not create route 172.16.130.64/27 for node cn-beijing.i-2ze8nyz28v9ydi0fx2iu: timed out waiting for the condition -> instance not found
```

fix route creation when the node is in unknown status

---

cloud-controller-manager/controller/route/controller.go

ignore idc node

---

cloud-controller-manager/alicloud.go
cloud-controller-manager/controller/route/controller.go
cloud-controller-manager/routes.go

delete route when node deleted

---

cloud-controller-manager/controller/service/controller.go
cmd/cloudprovider/app/ccm.go
vendor/github.com/denverdino/aliyungo/common/endpoint.go

1. set concurrent worker to 2
2. fix aliyungo concurrent map write
3. backoff requeue on throttle

Fix aliyungo concurrent map write. requeue backoff on throttle

---

cloud-controller-manager/instances.go
docs/getting-started.md

Add section on how to install alibaba cloudprovider when installing the cluster using rke
Minor fixes to the existing documentation

Adding documentation for rke set up and other documentation updates

---

cloud-controller-manager/controller/service/context.go

add debug info for node change event

---

pkg/controller/service/annotations.go
pkg/controller/service/listeners.go
pkg/model/load_balancer.go
pkg/provider/alibaba/slb/listener.go

service.beta.kubernetes.io/alibaba-cloud-loadbalancer-request-timeout
service.beta.kubernetes.io/alibaba-cloud-loadbalancer-established-timeout
service.beta.kubernetes.io/alibaba-cloud-loadbalancer-health-check-method

support annotations:

---

docs/examples/master.policy
docs/examples/worker.policy
docs/getting-started.md

update getting-started documentation

---

test/e2e/client/kubeclient.go

/kind bug
skip vk node in node test 
test failed in vk  ACK cluster
Fixes #
```release-note
```
```docs
```

test: skip vk node in node test

---

pkg/controller/service/model_applier.go

skip reconcile lb attribute when delete reused slb

---

pkg/controller/node/node_controller_test.go
pkg/controller/route/route_controller_test.go
pkg/controller/service/service_controller_test.go
pkg/provider/vmock/ecs.go

add node controller & route controller unit tests

---

Makefile
go.mod

Upgrade golangci-lint to v1.51.2
Fixes #
```release-note
```
```docs
```

upgrade golangci-lint to v1.51.2

---

pkg/controller/service/clbv1/vgroups.go
pkg/controller/service/nlbv2/server_groups.go

Fixes #
```release-note
```
```docs
```

remove serverip when type=ecs

---

pkg/controller/service/clbv1/listeners.go
pkg/model/load_balancer.go
pkg/provider/alibaba/slb/cert.go
pkg/provider/alibaba/slb/loadbalancer.go
pkg/provider/dryrun/slb.go
pkg/provider/provider.go
pkg/provider/vmock/slb.go

do not update cert if cert is expired

---

pkg/provider/dryrun/slb.go

do not create/add vservergroup in precheck

---

pkg/controller/service/clbv1/listeners.go
pkg/controller/service/reconcile/annotation/annotations.go
pkg/model/load_balancer.go
pkg/provider/alibaba/slb/listener.go

Fixes #
```release-note
```
```docs
```

feature: support close udp/tcp health check

---

pkg/provider/alibaba/slb/loadbalancer.go

add ascm context when creating slb

---

pkg/controller/service/clbv1/listeners.go
pkg/provider/alibaba/slb/listener.go
pkg/provider/dryrun/slb.go
pkg/provider/provider.go
pkg/provider/vmock/slb.go

Fixes #
```release-note
```
```docs
```

support tcp/udp mixed protocol

---

pkg/controller/service/clbv1/loadbalancer.go
pkg/controller/service/clbv1/model_applier.go
pkg/controller/service/nlbv2/loadbalancer.go
pkg/controller/service/nlbv2/model_applier.go

Fixes #
```release-note
```
```docs
```

if sync lb failed, continue to sync vgroup & listener

---

test/e2e/client/kubeclient.go
test/e2e/framework/expect_nlb.go
test/e2e/framework/framework.go
test/e2e/testcase/route/route.go
test/e2e/testcase/service/clbv1/backend.go
test/e2e/testcase/service/clbv1/listener.go
test/e2e/testcase/service/nlbv2/backend.go
test/e2e/testcase/service/nlbv2/listener.go

add e2etests

---

pkg/controller/service/clbv1/model_applier.go

Fixes #
```release-note
```
```docs
```

fix: when a service with eip annotation, it can not be updated.

---

pkg/controller/service/clbv1/vgroups.go
pkg/controller/service/nlbv2/server_groups.go
test/e2e/framework/expect.go
test/e2e/framework/expect_nlb.go

Fixes #
```release-note
```
```docs
```

fix: divide by zero

---

pkg/provider/alibaba/base/clientMgr.go

Fixes #
```release-note
```
```docs
```

feat: STS and NLB products use vpc endpoint

---

pkg/controller/helper/service_utils.go
pkg/controller/helper/service_utils_test.go

Fixes #
```release-note
```
```docs
```

feat: update compute hash func

---

pkg/controller/node/node_controller.go
pkg/controller/service/clbv1/service_controller.go

Fixes #
```release-note
```
```docs
```

feat: update controllerCFG

---

pkg/controller/helper/event.go
pkg/controller/service/clbv1/vgroups.go
pkg/controller/service/clbv1/vgroups_test.go
pkg/controller/service/nlbv2/server_groups.go
pkg/controller/service/reconcile/backend/backend.go
pkg/model/load_balancer.go
pkg/model/nlb/nlb.go
pkg/provider/vmock/slb.go

Fixes #
```release-note
```
```docs
```

feat: aggregate errors when sync clb&nlb backend servers

---

pkg/controller/service/clbv1/loadbalancer.go
pkg/controller/service/reconcile/annotation/annotations.go
pkg/model/load_balancer.go
pkg/provider/alibaba/slb/loadbalancer.go
test/e2e/framework/expect.go
test/e2e/options/options.go
test/e2e/testcase/service/clbv1/loadbalancer.go

/kind feature
Fixes #
```release-note
```
```docs
```

Support specify CLB ip address in annotation

---

pkg/controller/ingress/alb_controller.go
pkg/controller/ingress/reconcile/store/store.go

/kind cleanup
package  is being imported more than once 
Fixes #
```release-note
NONE
```
```docs
```

chore: chore: pkg imported more than once

---

pkg/provider/alibaba/elb/loadbalancer.go

kind/cleanup
This PR fixes a typographical error in the cloud-provider-alibaba-cloud/pkg/provider/alibaba/elb/loadbalancer.go file. The word "laodbalancer" has been corrected to "loadbalancer".
Fixes #
NONE
```release-note
```
```docs
```

fix: typo in loadbalancer

---

pkg/controller/service/clbv1/service_controller_test.go
pkg/controller/service/clbv1/vgroups.go
pkg/provider/alibaba/vpc/vpc.go
pkg/provider/dryrun/vpc.go
pkg/provider/provider.go
pkg/provider/vmock/vpc.go

Fixes #
```release-note
```
```docs
```

feat: filter pods whose ip not in vpc cidr in eni mod

---

pkg/config/controller_config.go
pkg/controller/service/clbv1/vgroups.go
pkg/controller/service/nlbv2/server_groups.go

Fixes #
```release-note
```
```docs
```

support configuring server group batch size

---

pkg/controller/route/route_controller_test.go

Fixes #
```release-note
```
```docs
```

test: update route controller tests

---

test/e2e/e2e_test.go
test/e2e/framework/expect.go
test/e2e/framework/expect_nlb.go
test/e2e/testcase/service/clbv1/loadbalancer.go
test/e2e/testcase/service/nlbv2/backend.go

Fixes #
```release-note
```
```docs
```

add nlb ip tests; update expect to support paybyclcu & serverGroupTDype

---

pkg/controller/helper/event.go
pkg/controller/service/clbv1/vgroups.go
pkg/provider/alibaba/vpc/vpc.go
pkg/provider/dryrun/vpc.go
pkg/provider/provider.go
pkg/provider/vmock/vpc.go

Fixes #
```release-note
```
```docs
```

support vpc with secondary cidrs

---

pkg/controller/node/manager.go
pkg/controller/service/clbv1/event_handler.go
pkg/controller/service/nlbv2/event_handler.go
pkg/controller/service/reconcile/backend/backend.go

/kind feature
Fixes #
```release-note
```
```docs
```

add resourceVersion=0 for list requests

---

test/e2e/testcase/service/nlbv2/backend.go

/kind bug
/kind failing-test
Fixes #
```release-note
```
```docs
```

set HealthCheckInterval to 5 to fix e2e error

---

pkg/controller/node/manager.go
pkg/controller/node/node_controller.go

Fixes #
```release-note
```
```docs
```

bugfix: fix node controller do not init routeconfig

---

pkg/config/feature_gates.go

/kind feature
Fixes #
```release-note
```
```docs
```

enable EndpointSlice feature by default

---

pkg/config/feature_gates.go
pkg/controller/service/clbv1/event_handler.go
pkg/controller/service/nlbv2/event_handler.go

/kind feature
Fixes #
```release-note
```
```docs
```

filter services when node reconcile

---

pkg/controller/helper/net_utils.go
pkg/controller/helper/node_utils.go
pkg/controller/node/node_controller.go
pkg/provider/alibaba/ecs/ecs.go

/kind feature
Fixes #
```release-note
```
```docs
```

node add ipv6 address

---

pkg/provider/alibaba/nlb/loadbalancer.go
pkg/provider/alibaba/slb/loadbalancer.go

Fixes #
```release-note
```
```docs
```

check loadbalancer id from API when reuse

---

pkg/config/cloud_config.go
pkg/controller/route/manager.go
pkg/controller/route/manager_test.go
pkg/controller/service/clbv1/loadbalancer.go
pkg/controller/service/nlbv2/loadbalancer.go
pkg/controller/service/nlbv2/server_groups.go
pkg/provider/alibaba/nlb/servergroup.go

/kind feature
Fixes #
```release-note
```
```docs
```

create with specified resource group id for clb&nlb 

---

pkg/config/cloud_config.go
pkg/config/controller_config.go
pkg/controller/node/event_handler.go
pkg/controller/node/node_controller.go
pkg/controller/service/clbv1/service_controller.go
pkg/controller/service/nlbv2/nlb_controller.go
pkg/util/log.go

/kind feature
support set `NodeMaxConcurrentReconciles` in cloud config file

add node max syncs in cloud config

---

pkg/controller/service/nlbv2/model_applier.go
pkg/provider/alibaba/nlb/loadbalancer.go

/kind feature
release note
```
support reuse nlb with another vpc
```

feat: support reusing nlb of another vpc

---

pkg/controller/service/nlbv2/loadbalancer.go
pkg/controller/service/nlbv2/model_applier.go
pkg/controller/service/nlbv2/server_groups.go
pkg/controller/service/reconcile/annotation/annotations.go
pkg/controller/service/reconcile/backend/backend.go
pkg/model/nlb/nlb.go
pkg/provider/alibaba/ecs/ecs.go
pkg/provider/alibaba/nlb/loadbalancer.go
pkg/provider/dryrun/nlb.go
pkg/provider/provider.go
pkg/provider/vmock/nlb.go
test/e2e/framework/expect_nlb.go
test/e2e/options/options.go
test/e2e/testcase/service/nlbv2/loadbalancer.go

/kind feature
Fixes #
```release-note
```
```docs
```

nlb ipv6 backend & address type support

---

pkg/controller/service/clbv1/listeners.go
pkg/controller/service/clbv1/vgroups.go
pkg/controller/service/nlbv2/listeners.go
pkg/controller/service/nlbv2/model_applier.go
pkg/controller/service/nlbv2/server_groups.go
pkg/provider/alibaba/nlb/servergroup.go
pkg/provider/dryrun/nlb.go
pkg/provider/provider.go
pkg/provider/vmock/nlb.go
test/e2e/framework/expect_nlb.go
test/e2e/options/options.go
test/e2e/testcase/service/nlbv2/backend.go

/kind feature
Fixes #
```release-note
```
```docs
```

support nlb vgroup-port and weight & fix clb listener vgroup reuse

---

pkg/controller/service/reconcile/backend/backend.go

Fixes #
```release-note
```
```docs
```

fix backend ip version check for clb

---

pkg/controller/service/clbv1/service_controller.go
pkg/controller/service/nlbv2/nlb_controller.go
pkg/util/metric/metrics.go

Fixes #
```release-note
```
```docs
```

metrics: clb latency&operation related metrics

---

Dockerfile
go.mod
go.sum

/kind feature
update go version to 1.22
```release-note
```
```docs
```

update go version to 1.22.0

---

pkg/controller/service/nlbv2/listeners.go
pkg/controller/service/reconcile/annotation/annotations.go
pkg/provider/alibaba/nlb/listener.go
pkg/provider/provider.go
test/e2e/framework/expect_nlb.go
test/e2e/testcase/service/nlbv2/listener.go

Fixes #
```release-note
```
```docs
```

nlb support alpn

---

pkg/config/feature_gates.go
pkg/controller/helper/service_utils.go

Fixes #
```release-note
```
```docs
```

support nlb for `service.beta.kubernetes.io/class` annotation

---

go.mod
pkg/controller/helper/event.go
pkg/controller/service/clbv1/loadbalancer.go
pkg/controller/service/clbv1/model_applier.go
pkg/controller/service/clbv1/model_builder.go
pkg/controller/service/clbv1/service_controller.go
pkg/controller/service/nlbv2/loadbalancer.go
pkg/controller/service/nlbv2/model_applier.go
pkg/controller/service/nlbv2/model_builder.go
pkg/controller/service/nlbv2/server_groups.go
pkg/controller/service/reconcile/annotation/annotations.go
pkg/model/load_balancer.go
pkg/model/nlb/nlb.go
pkg/provider/alibaba/nlb/loadbalancer.go
pkg/provider/alibaba/nlb/servergroup.go
pkg/provider/alibaba/slb/loadbalancer.go
pkg/provider/dryrun/nlb.go
pkg/provider/dryrun/slb.go
pkg/provider/provider.go
pkg/provider/vmock/nlb.go
pkg/provider/vmock/slb.go
test/e2e/testcase/service/nlbv2/loadbalancer.go

Fixes #
```release-note
```
```docs
```

preserve lb on delete for clb&nlb

---

pkg/controller/service/clbv1/service_controller.go
pkg/controller/service/nlbv2/nlb_controller.go

Fixes #
```release-note
```
```docs
```

check loadbalancer class again to cleanup

---

pkg/controller/service/clbv1/model_applier.go
pkg/controller/service/clbv1/service_controller.go
pkg/controller/service/nlbv2/nlb_controller.go
pkg/controller/service/reconcile/context/request_context.go
pkg/provider/alibaba/nlb/loadbalancer.go
pkg/provider/alibaba/slb/loadbalancer.go

Fixes #
```release-note
```
```docs
```

add extra info to reconcile logs

---

test/e2e/testcase/service/nlbv2/listener.go
test/e2e/testcase/service/nlbv2/loadbalancer.go

Fixes #
```release-note
```
```docs
```

fix e2e test compile error and failure

---

pkg/controller/node/manager.go
pkg/controller/node/node_controller_test.go
pkg/provider/alibaba/ecs/ecs.go
pkg/provider/provider.go
pkg/provider/vmock/ecs.go

Fixes #
```release-note
```
```docs
```

add spot strategy label to node

---

pkg/controller/service/clbv1/service_controller.go
pkg/controller/service/nlbv2/nlb_controller.go

Fixes #
```release-note
```
```docs
```

skip update pod readiness conditions when it not found

---

pkg/controller/service/clbv1/loadbalancer.go
pkg/controller/service/nlbv2/loadbalancer.go
pkg/provider/alibaba/nlb/loadbalancer.go
pkg/provider/alibaba/slb/loadbalancer.go
pkg/provider/dryrun/nlb.go
pkg/provider/provider.go
pkg/provider/vmock/nlb.go
test/e2e/framework/framework.go

Fixes #
```release-note
```
```docs
```

add resourceVersion as part of client token

---

pkg/controller/service/clbv1/model_applier.go
pkg/controller/service/nlbv2/model_applier.go
pkg/provider/alibaba/slb/vgroup.go
pkg/provider/vmock/slb.go

Fixes #
```release-note
```
```docs
```

skip already updated server groups

---

pkg/controller/service/nlbv2/nlb_controller.go

Fixes #
```release-note
```
```docs
```

fix nlb readiness gate retry

---

pkg/provider/alibaba/base/clientMgr.go

Fixes #
```release-note
```
```docs
```

support custom nlb endpoint from env

---

pkg/provider/alibaba/nlb/loadbalancer.go

Fixes #
```release-note
```
```docs
```

use nil when allocation id and ipv4 addr not specified

---

pkg/controller/service/clbv1/vgroups.go
pkg/controller/service/nlbv2/server_groups.go
pkg/controller/service/reconcile/annotation/annotations.go
pkg/model/load_balancer.go
pkg/model/nlb/nlb.go
test/e2e/testcase/service/clbv1/backend.go
test/e2e/testcase/service/nlbv2/backend.go

Fixes #
```release-note
```
```docs
```

support ignore backend weight update

---

pkg/config/cloud_config.go
pkg/config/controller_config.go
pkg/controller/node/manager.go
pkg/controller/node/node_controller.go
pkg/controller/route/event_handler.go
pkg/controller/route/manager.go
pkg/controller/route/predicate.go
pkg/controller/route/route_controller.go
pkg/model/route.go
pkg/provider/alibaba/alibabacloud.go
pkg/provider/alibaba/ecs/ecs.go
pkg/provider/alibaba/vpc/vpc.go
pkg/provider/dryrun/vpc.go
pkg/provider/provider.go
pkg/provider/vmock/ecs.go
pkg/provider/vmock/mockcloud.go
pkg/provider/vmock/vpc.go

batch process for node and route controller & refactor disable node source dest check
Signed-off-by: xiayu.lyt <lyt1999131@163.com>
Fixes #
```release-note
```
```docs
```

batch process for node and route controller

---

pkg/config/controller_config.go
pkg/controller/helper/event.go
pkg/controller/helper/finalizer.go
pkg/controller/helper/service_utils.go
pkg/controller/node/node_controller.go
pkg/controller/service/clbv1/model_applier.go
pkg/controller/service/clbv1/model_applier_test.go
pkg/controller/service/clbv1/service_controller.go
pkg/controller/service/clbv1/service_controller_test.go
pkg/controller/service/clbv1/vgroups.go
pkg/controller/service/clbv1/vgroups_test.go
pkg/controller/service/nlbv2/listeners.go
pkg/controller/service/nlbv2/model_applier.go
pkg/controller/service/nlbv2/server_groups.go
pkg/controller/service/reconcile/parallel/parallel.go
pkg/provider/alibaba/nlb/listener.go
pkg/provider/alibaba/nlb/loadbalancer.go
pkg/provider/alibaba/nlb/servergroup.go
pkg/provider/alibaba/util/helper.go
pkg/provider/dryrun/nlb.go
pkg/provider/provider.go
pkg/provider/vmock/nlb.go
test/e2e/framework/expect.go
test/e2e/testcase/service/nlbv2/listener.go

and fix e2e failure for nlb listener idletimeout
Signed-off-by: xiayu.lyt <lyt1999131@163.com>
Fixes #
```release-note
```
```docs
```

paralleize listener and servergroup actions

---

pkg/controller/service/clbv1/vgroups.go
pkg/controller/service/nlbv2/server_groups.go
test/e2e/client/kubeclient.go
test/e2e/framework/expect.go
test/e2e/framework/expect_nlb.go
test/e2e/testcase/service/clbv1/backend.go
test/e2e/testcase/service/nlbv2/backend.go

Fixes #
```release-note
```
```docs
```

fix named port & add e2e tests

---

pkg/config/controller_config.go
pkg/provider/alibaba/base/metadata.go

Signed-off-by: xiayu.lyt <lyt1999131@163.com>
Fixes #
```release-note
```
```docs
```

support for imdsv2

---

pkg/controller/service/clbv1/loadbalancer.go
pkg/model/load_balancer.go

Fixes #
```release-note
```
```docs
```

change CLB default instance charge type from PayBySpec to PayByCLCU

---

pkg/util/reconcile.go

Fixes #
```release-note
```
```docs
```

change readiness gate requeue to fixed interval

---

pkg/controller/helper/node_utils.go
pkg/controller/ingress/reconcile/backend/endpoint_resolver.go
pkg/controller/node/manager.go
pkg/controller/node/manager_test.go
pkg/controller/route/manager.go
pkg/controller/route/predicate.go
pkg/controller/service/clbv1/event_handler.go
pkg/controller/service/clbv1/vgroups.go
pkg/controller/service/nlbv2/event_handler.go
pkg/controller/service/nlbv2/server_groups.go
test/e2e/client/kubeclient.go
test/e2e/framework/expect.go

Fixes #
```release-note
```
```docs
```

ignore hybrid node type

---

pkg/controller/service/nlbv2/loadbalancer.go
pkg/provider/alibaba/nlb/loadbalancer.go
pkg/provider/alibaba/vpc/vpc.go
test/e2e/framework/expect_nlb.go
test/e2e/framework/framework.go
test/e2e/options/options.go
test/e2e/testcase/service/nlbv2/loadbalancer.go

Fixes #
```release-note
```
```docs
```

support AllocationId and PrivateIPv4Address for zonemaps

---

pkg/config/controller_config.go
pkg/controller/helper/service_utils.go
pkg/controller/helper/service_utils_test.go
pkg/controller/service/clbv1/event_handler.go

Signed-off-by: xiayu.lyt <lyt1999131@163.com>
Fixes #
```release-note
```
```docs
```

add flag to ignore service with tunnel-type annotation
